### PR TITLE
Faux Pas integration

### PR DESCRIPTION
**Pull request by zippy1978**
**Note: this PR replaces my previous one**

Hi,

Here is a PR to add Faux Pas support (http://fauxpasapp.com/) to the plugin.
Here are the details:
- Moved OCLint related classes to plugins.objectivec.violations.oclint package
- Added FauxPas classes into plugins.objectivec.violations.fauxpas package
- Plugin now creates a generic 'Objective-C' default profile including both FauxPas and OCLint rules
- Created updateFauxPasRules.groovy script to create / update FauxPas rules repository
- Added FauxPas rules to SQALE model
- Updated run-sonar.sh to run fauxpas command (if installed)

Gilles

### CODE REVIEW

**Comment by cyrilpicat** [comment]
Hello Gilles,

thanks a lot for this pull request.

I did not know much about this tool. I will test your PR and merge it next week.

Cheers,

**Comment by tbores** [comment]
Hello,
any news about the integration of this pull request?

**Comment by cyrilpicat** [comment]
you are right, I will merge it in the trunk quickly, and plan a new version of the plugin soon, hopefully this week or next week.

thanks for the heads up,

sorry for the delay

**Comment by tbores** [comment]
Thanks for your quick answer. We will also post a new Pull Request next week for the implementation of the Complexity Metric (https://github.com/agh92/sonar-objective-c/tree/lizard_complexity). But first we have to finish the Unit Tests.

**Comment by sarang1991** [comment]
In my project directory sonar-report/oclint is not created, when i executing sonar-runner. So that in sonar no violations listed. But when i manually executing commands  like 
xcodebuild clean build > xcodebuild.log

oclint-xcodebuild

oclint-json-compilation-database  -- -report-type pmd -o oclint.xml

i got oclint.xml. then i created a sonar-report folder in project directory and pasted oclint.xml. Then i got violations listed in my sonar. why file not found exception occures ? why no folder created ? how can i execute above three commands to generate oclint.xml ? wher to add those commands? please give your valuable suggestions.

**Pull request closed without merging**
