### PR TITLE
Sonar 5.0 support

### PR DESCRIPTION
**Pull request by zippy1978**
Removed deprecations
- commons-configuration by Settings
- Rewrote **shouldExecuteOnProject** sensor methods

### CODE REVIEW

**Comment by zippy1978** [comment]
I have tested on:
 * 4.3.3
 * 4.5.1

And it runs fine...
I have not tested 3.7.1

**Comment by cyrilpicat** [comment]
ok, thanks, I will test it on my side

**Comment by cyrilpicat** [comment]
Hi Gilles,

After testing it, the latest plugin works only with Sonar >= 4.3 (which is ok). I have updated the documentation to reflect this.

On another topic, I revert your change in run-sonar.sh (local directory for building) as it was not working in my sample projects. I did not took time to investigate, sorry.

Why did you make this change? The old script wasn't working in your case?

I released the plugin in that state to get some feedback from users. I am sure there will be a need for a 0.4.1 release soon anyway.

thanks a lot for your work by the way!

**Comment by zippy1978** [comment]
Hi Cyril,

Nice :)

I modified the run-sonar.sh script because after enabling Sonar analysis on many projects of my company, I noticed 2 issues:

First, I noticed that the code coverage was not right because some classes where ignored by the report. And I noticed the problem did not happen on my company CI server (using xctool and gcovr as well). So, after a quick analysis : I found that the only difference was the way of building (using a local directory). I don't really know why, but using a local build directory fixed the problem.

Then, I also noticed that the xctool command failed to run tests on big projects (more than 20000 loc, and hundred of tests): it returned 1 as return code, although the test report was ok (maybe a bug with xctool). The workaround I found (not the best) was not testing return code on that command.

**Pull request merged**
